name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, world!"
      - uses: actions/checkout@v2
      - name: Run tests
        run: npm test
